import "./globals.css";


export const metadata = {
  title: "Lakshya Tyagi :)",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#252525] text-gray-50">
      <body>{children}</body>
    </html>
  );
}
